### ISSUE TITLE
win 10 npm run tsc error ,why?

### ISSUE THREAD

**Issue by smile2014** [udos86/ng2-dynamic-forms#101]
node_modules/@angular2-material/button/button.d.ts(28,14): error TS1005: '=' expected.

**Comment by udos86** [comment]
@smile2014 This is an error in Angular 2 Material concerning `readonly` modifier. I guess it's because they're already using TypeScript 2.0 while we're still on TypeScript 1.8 (see [`readonly` declaration in TypeScript 2.0](https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#read-only-properties-and-index-signatures)

**Comment by smile2014** [comment]
@udos86  thank you
