### ISSUE TITLE
basic ui: container element incorrectly has ng-invalid class

### ISSUE THREAD

**Issue by johngrimsey** [udos86/ng2-dynamic-forms#186]
I'm not 100% sure this is an issue but it doesn't feel right...

When a container element contains an invalid input element, the container correctly has the class `ng-invalid`. The invalid input element also has the class `ng-invalid`. 

When the invalid input's value becomes valid the `ng-invalid` class is removed and the `ng-valid` class applied – but – the _container_ element still has `ng-invalid` - I would expect the container to now have the class `ng-valid` instead.

It appears that an input element's container is considered 'invalid' if the whole form is invalid?

**Comment by udos86** [comment]
@johngrimsey Thanks for your message! However I cannot confirm this behavior in [live example](http://ng2-dynamic-forms.udos86.de/example/#/example-bootstrap)

**Comment by johngrimsey** [comment]
Hi! Yes it works nicely in the live example. I'll try and find the time to isolate and describe in more detail.

**Comment by johngrimsey** [comment]
To reproduce you can try creating a form with a DynamicFormGroupModel which contains nine DynamicInputModel elements that are all required. 

When an input element has classes `ng-valid ng-touched ng-dirty`, the container element and its parent fieldset both have classes `ng-dirty ng-touched ng-invalid`.

When the input becomes valid I'd expect the fieldset to have ng-invalid but the container element should have ng-valid?

**Comment by udos86** [comment]
@johngrimsey Alright. Hope I'll find the time to check it out this weekend.

**Comment by johngrimsey** [comment]
Thanks @udos86 I appreciate it

**Comment by udos86** [comment]
@johngrimsey Ok, I could reproduce this. I wouldn't consider this an actual bug.  The (div) container needs to be internally bound to the form group. That's why the css classes of the container correspond to the status of the entire form group. 

Nevertheless I understand that you would expect it to refer to the current status of the form control instead. However I don't see any chance on changing this behavior.

Anyway thanks for finding this out!
