### ISSUE TITLE
Feature request: multi select input

### ISSUE THREAD

**Issue by stefanmeschke** [udos86/ng2-dynamic-forms#187]
Hi,

first of all, thank you for this library.
We need a multi select input. Are there any plans for this?
Or should we do this on our own and create a pull request?

Cheers!

==========
- [x] ui-kendo
- [x] ui-material
- [x] ui-primeng

**Comment by udos86** [comment]
@stefanmeschke Thanks for your message! This is planned for Material 2 and Kendo UI as soon as those UI libraries are going to support it. Really appreciate your will to contribute but without a corresponding UI component there cannot be corresponding dynamic control model in ng2 Dynamic Forms.

**Comment by udos86** [comment]
@stefanmeschke I've prepared `DynamicSelectModel` to support multiple selections. However there is an issue in Angular 2 not allowing single values on form controls whenever applying `multiple` attribute to native selects. That's why I don't like to introduce it to `ui-basic`, `ui-bootstrap` and `ui-foundation` yet, as this would lead to a breaking change. However `ui-material`, `ui-kendo` and`ui-primeng` will get support in the near future.

**Comment by stefanmeschke** [comment]
@udos86 Thank you for your feedback. We've done it on our own with a Selectize-Directive and other custom form elements. At this point we have to pull, merge and edit all files in @ng2-dynamic-forms/ui-bootstrap to enable our custom form elements.

**Comment by udos86** [comment]
- [ ] ui-kendo
- [ ] ui-material
- [ ] ui-primeng

**Comment by drkhannah** [comment]
is there support for multi select in bootstrap yet? It is a common form control of the bootstrap lib, and I don't want to have to use a ton of checkboxes

**Comment by Vbboi24** [comment]
Hey, Is there any update on this? The multi select dropdown for primeng is still not working
