### ISSUE TITLE
Creating FormArray with default values

### ISSUE THREAD

**Issue by donaldinho** [udos86/ng2-dynamic-forms#291]
Hi there.

I'm wanting to create a FormArray of inputs and pre-populate different values for each form element in the FormArray but I do not want to have to use the FormService to do this. Is this possible?

Thanks in advance

**Comment by udos86** [comment]
@donaldinho Hi!

It's not possible by configuration but can be easily achieved by using [`valueUpdates`](https://github.com/udos86/ng2-dynamic-forms#model-bindings-and-control-references).

**Comment by donaldinho** [comment]
@udos86 
Thanks for your response. I have a load of different forms that I need to save in a database so it's quite a lot of work to implement setting all the different values in code. I was wanting to be able to recreate my forms just by passing a config into createFormGroup or by using fromJSON
Currently I'm creating json for the form layouts I need and using fromJSON. This obviously works. I just wondered if there was another way to do it.
I'm currently experimenting with how much I can trim down the json and still get my layouts loaded.  Is this something you've considered officially supporting - creating the configuration from JSON? If it was it would be good to be able to pass in only the info that was required. For instance if there is nothing set in the cls object
```
"cls": {
            "element": {
                "container": "" ,
                "control": "" ,
                "errors": "" ,
                "hint": "" ,
                "label": ""
            } ,
            "grid": {
                "container": "" ,
                "control": "" ,
                "errors": "" ,
                "hint": "" ,
                "label": ""
            }
        } ,
```
we would not have to pass it in. Currently if there is no cls object an error is thrown so I'm passing in
```
"cls": {
            "element": { } ,
            "grid": { }
        },
```

**Comment by udos86** [comment]
@donaldinho 
Thanks for your explaining your use case and diving deeper into the source code! 

When I designed the library I had to make a decision wether to base model configuration on constructor functions or plain JSON objects. 

I'm still convinced that prototypal inheritance brings a lot of advantages but I'd also like to provide the alternative way in the future. However I really haven't made up a plan on how to combine both approaches.

Nevertheless you should already be able to create a form array with prefilled values from JSON by using a configuration like this:

```
{
  "cls": {
  },
  "id": "sampleFormArray",
  "label": "Sample Array Model",
  "groups": [
    {
      "group": [
        {
          "cls": {...},
          "id": "sampleArrayGroupInput",
          "value": "one",
          "type": "INPUT"
        }
      ],
      "index": 0
    },
    {
      "group": [
        {
          "cls": {...},
          "id": "sampleArrayGroupInput",
          "value": "two",
          "type": "INPUT"
        }
      ],
      "index": 1
    },
    {
      "group": [
        {
          "cls": {...},
          "id": "sampleArrayGroupInput",
          "value": "three",
          "type": "INPUT"
        }
      ],
      "index": 2
    }
  ],
  "type": "ARRAY",
  "originGroup": [
    {
      "cls": {...},
      "id": "basicArrayGroupInput"
    }
  ]
}
```

**Comment by udos86** [comment]
@donaldinho Ah and thanks for the hint concerning `cls` attribute. I'll improve that.

**Comment by gms1** [comment]
@udos86
maybe you can remember me, I had a similar use case some weeks ago (backend plugins requiring special configuration data filled out by the user). For time reasons, I then proceeded as follows:
The form is read as JSON by the DynamicFormService, but I use a JSON pointer for the id-field of all DynamicFormValueControlModels.
Using this, my GenericFormService is able to fill the form fields from a JSON object and write the form values into a JSON object

Your project is awesome and I believe for the implementation of such additional features you can build very well on the existing functionality, so that with little effort the scope of application could be extended

If you are willing to accept pull requests for a new module ( 'ng2-dynamic-forms/generic' for instance ) I would like to contribute.

however, we would need a decision on how the mapping should be implemented:
A) Parsing remains in the 'core' with an additional optional field for the JSON pointer ( the name of this field can be kept neutral, like 'userData' )
B) The new module gets its own implementation for parsing the JSON form, so the mapping can be kept completely outside of the 'core' module
C) other ideas ...

**Comment by udos86** [comment]
@gms1 Thanks for your message, I do remember! 

I'd be glad if someone could take this over. What do you think would be the better solution? A or B? Could I have a look at the source code for your JSON pointer?

**Comment by udos86** [comment]
Closed due to inactivity
