### ISSUE TITLE
Question: How to access each control inside a specific group?

### ISSUE THREAD

**Issue by rafaelss95** [udos86/ng2-dynamic-forms#352]
Hello,

I have the following control model:

```
public model: DynamicFormControlModel[] = [
  new DynamicFormGroupModel({
    id: 'basicFormGroup1',
    legend: 'Form Group 1',
    group: [
      new DynamicInputModel({
        id: 'exampleInput',
        label: 'Example Input',
        validators: {
          required: null,
          minLength: 3
        },
        placeholder: 'example input',
      })
      // Another fields
    ]
  })    
];
```

And in template:

```
<div *ngFor="let controlModel of model">
  <dynamic-form-material-control #componentRef="" [group]="formGroup" [model]="controlModel">
    <app-form-validation [control]="componentRef.control"></app-form-validation>
  </dynamic-form-material-control>
</div>
```
I want to access each _control_ inside my group "basicFormGroup1". Actually when I access `componentRef.control` in my validation _component_ it shows me the whole **group**.

So, is there a way to pass each control in template?

PS: I searched it in docs and I didn't found a way.

Thanks in advance :)

**Comment by udos86** [comment]
@rafaelss95 THANKS for giving the library a try!

I'm afraid your constellation comes up against the limits of Angular's transclusion feature.

The problem here is that ng2 Dynamic Forms internally resolves a `DynamicFormGroupModel` recursively while the transcluded content via `<ng-content>` cannot be forwarded to a nested component.

You would have to pass on the `DynamicFormGroupModel` to make it work. 

Furthermore you could also activate the built-in error messaging by binding `[hasErrorMessaging]`.
