### ISSUE TITLE
Input text masking

### ISSUE THREAD

**Issue by amit-kadam** [udos86/ng2-dynamic-forms#379]
Hi,

We are using ng2-dynamic-forms (v1.4.11) with ng4, We are looking for input text masking feature with dynamic form.
e.g.

![image](https://cloud.githubusercontent.com/assets/16774743/26723366/cfbad54a-47b1-11e7-8c4f-b4d74a5f45ef.png)

When user focuses input, placeholder moves up and mask pattern appears for input.

Within ng2-dynamic-forms, 'mask' configuration property is available within DynamicInputModelConfig. However it looks it is not utilized further. 

Good to have this feature added in ng2-dynamic-forms or at least a doc on how to use third party plugins like https://github.com/T3KN0KRAT/text-mask

Thanks in advance.

**Comment by udos86** [comment]
@amit-kadam Thanks for using the library!

The `mask` property only works in conjunction with a UI component that supports such a feature. Currently this is only the case for Kendo (and PrimeNG).  

Adding an extension like text-mask to pure CSS-based UI packages like `ui-bootstrap` is basically a good idea. However the problem is that Angular so far does not support conditional directives. As soon as this is the case your issue would be a legitimate feature request.

**Comment by bkinsey808** [comment]
I hope we can do this. I would love to see text-mask support at least for the material module. It's a solid masking solution, the best I've found for angular material 2. I'm not sure how I can accomplish support for it with ng2-dynamic-forms short of forking.

**Comment by udos86** [comment]
@bkinsey808 

> I hope we can do this. I would love to see text-mask support at least for the material module.

I gave it a try today. Looks promising but I could not get it running in conjunction with dynamic component template yet.

**Comment by udos86** [comment]
@amit-kadam @bkinsey808 

Alright, let's do this! 

`1.4.12` will deliver initial support for text masks! Thanks for bringing up this idea.

**Comment by bkinsey808** [comment]
Just a thought: is there a way to solve this in the general case? There are a universe of directives we might want to add to a control. Is there a way to add custom directives like this:

  [textMask]="{mask: mask}"

Where we can define both the left and the right side in the control definition?

**Comment by udos86** [comment]
@bkinsey808 No chance. Angular does not support such a dynamic directive approach.

**Comment by bkinsey808** [comment]
Apparently multiple directives can be condensed into a single directive. Not sure if this is possible, but can you imagine being able to pass in an array of directives and their values and having them condensed to a single directive? https://stackoverflow.com/questions/41618197/consolidating-two-directives-into-a-single-one/41650302#41650302

**Comment by amit-kadam** [comment]
Thanks @udos86 for your valuable support and providing latest change @1.4.12 . We saw the change log and realized that Basic, Bootstrap, Foundation, Ionic and NGBootstrap are enhanced for textmask. It would be great if support is extended for Material as well in future release. 

Others - Thanks for your inputs in this regards.

Thanks Again!

**Comment by udos86** [comment]
@amit-kadam Thanks!

I had already added text mask directive to the Material UI template when I realized some problems occurring. That's why I left it out in `1.4.12`. I'll have another look. 

@bkinsey808 Thanks for the info!

> can you imagine being able to pass in an array of directives and their values and having them condensed to a single directive?

Sorry, not for now. I'm still hoping for Angular core to deliver some kind of dynamic directives.

**Comment by amit-kadam** [comment]
@udos86 Thanks! Any updates on text mask directive for the Material UI template?

**Comment by cab-peax** [comment]
@udos86 Text Mask support for Material UI would be wonderful. I'm waiting eagerly for it! 👍
