### ISSUE TITLE
error when using universal

### ISSUE THREAD

**Issue by guzuomuse** [udos86/ng2-dynamic-forms#399]
hi @udos86 
i flow this [repo](https://github.com/evertonrobertoauler/cli-universal-demo) for universal usage.
with this ng2-dynamic-forms/core and bootstrap ui;
it gives these error:

> D:\pathofmine\node_modules\@ng2-dynamic-forms\core\src\core.module.js:7
> import { CommonModule } from angular/common;
> ^^^^^^
> 
> SyntaxError: Unexpected token import
>     at createScript (vm.js:74:10)
>     at Object.runInThisContext (vm.js:116:10)
>     at Module._compile (module.js:533:28)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:503:32)
>     at tryModuleLoad (module.js:466:12)
>     at Function.Module._load (module.js:458:3)
>     at Module.require (module.js:513:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (D:\pathofmine\dist\server.js:9142:18)
> error Command failed with exit code 1.

it seems that the  

 **core.module.js** file not be compiled completely,it still has some syntax such as 

```
import { CommonModule } from "@angular/common";
import { NgModule } from "@angular/core";
import { ReactiveFormsModule } from "@angular/forms";
```
maybe this library should be compiled to regular js file with babel or webpack...?
any idea to use this fantatic library for universal usage?

**Comment by guzuomuse** [comment]
@udos86  ,after a struggled in pain,i have found this works:
in webpack.confi add these line:

>   externals: [nodeExternals({
>     whitelist: [
>       /^@ng2-dynamic-forms\/core/,
>       /^@ng2-dynamic-forms\/ui-bootstrap/
>     ]
>   })],
thanks to the GOD!

**Comment by udos86** [comment]
@guzuomuse Thanks for your kind words!

I've not tried out Angular Universal so I'm glad for your expertise here.

All library packages comes with two different bundles:

* `*.es.js`: ES5 with ES2015 Modules for better Tree-Shaking 
* `*.umd.js`: UMD bundle with AMD, CommonJS and Globals support

Since Webpack 2 and Rollup are both capable of handling ES2015 module syntax I would not assumed any problems here. 

In fact, the sample app itself can be bundled with [Webpack 2](https://github.com/udos86/ng2-dynamic-forms/blob/master/webpack.config.js) and [Rollup](https://github.com/udos86/ng2-dynamic-forms/blob/master/rollup.config.js) without any problems.

**Comment by guzuomuse** [comment]
@udos86 ,thanks for your help.
since it's settled.  this issue would be closed
